version: '3'

services:
  mailer:
    build: .
    environment:
      - APP_NAME=mailer
    links:
      - rabbitmq
    volumes:
      - ./src:/usr/src/app
    command: sleep 3600

  rabbitmq:
    image: rabbitmq:3.6.14-management-alpine
    ports:
      - 15672:15672
